version: '3.8'

services:
  dev:
    container_name: tellaweb_api_dev
    image: tellaweb-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile.dev
    command: npm run start:debug
    ports:
      - 3001:3001
      - 9229:9229
    networks:
      - api-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: tellaweb_api_prod
    image: tellaweb-api-prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn start:prod
    ports:
      - 3001:3001
      - 9229:9229
    networks:
      - api-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"    
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - api-network
  redis:
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    networks:
      - api-network
    expose:
      - '6379'
    ports:
      - 6379:6379
    volumes: 
      - redis-data:/data
      
networks:
  api-network:

volumes:
  db-data:
  redis-data: