version: '3.8'

services:
  prod:
    container_name: tellaweb_api_prod
    image: tellaweb-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn start:prod
    ports:
      - 3001:3001
      - 9229:9229
    networks:
      - api-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  api-network:
