version: 2
jobs:
  build:
    working_directory: /$DOCKER_REPO
    docker:
      - image: docker:20.10.16-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=20.3.4-r1
            pip install docker-compose==1.29.2
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run $DOCKER_REPO npm run test
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_TOKEN
            docker tag dockerapp_dockerapp $DOCKER_USER/$DOCKER_REPO:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_USER/$DOCKER_REPO:latest
            docker push $DOCKER_USER/$DOCKER_REPO:$CIRCLE_SHA1
            docker push $DOCKER_USER/$DOCKER_REPO:latest
